Update `CONTRIBUTING.md`
humphd/my-photohub pull request #36
Opened 2022-12-10 03:39 UTC by rudychung

Addresses #32 

I'm sure I missed a few things, let me know if there's anything else you want me to add to the document.

2022-12-10 08:38 UTC, batunpc requested changes
Hi @rudychung, your instructions looking good! I just have found very minor issue and rephrased the sentence. 

Other than that It looks good!

2022-12-10 08:38 UTC, batunpc commented on CONTRIBUTING.md
> +Install [Node.js](https://nodejs.org/) if you haven't already, and run to install project dependencies:
Maybe we could rephrase the sentence like 

Install [Node.js](https://nodejs.org/) if you haven't already, and run the following command to install project dependencies:

2022-12-13 14:19 UTC, batunpc approved these changes

2022-12-14 18:40 UTC, SerpentBytes requested changes
I left some feedback.

2022-12-14 18:40 UTC, SerpentBytes commented on CONTRIBUTING.md
> +
Is it possible to restructure the document so that the "How to Contribute" section appears before "Getting Started"?

2022-12-14 23:41 UTC, SerpentBytes approved these changes

2023-04-19 20:51 UTC, closed without merging